- name: Create sudo user
  hosts: all
  tasks:
     - name: Change user password
       user: 
          name: "{{ user }}"
          update_password: always 
          password: "{{ new_password|password_hash('sha512') }}"
