---
- hosts: local_host
  gather_facts: false
  vars:
    ssh_key_content: ""

  tasks:
    - name: check .ssh local directory exists
      stat:
        path: "/home/{{USER}}/.ssh"
      register: ssh_directory_exists_check

    # - debug:
    #     var: ssh_directory_exists_check

    - name: check .ssh key file exists
      stat:
        path: "/home/{{USER}}/.ssh/{{item}}"
      register: ssh_key_file_exists_check
      with_items:
        - "{{USER}}"
        - "{{USER}}.pub"

    - name: fail if .ssh key is missing
      fail:
        msg: "the {{USER}}.pub was NOT found in .ssh folder"
      when: ssh_key_file_exists_check.results[1].stat.exists == false

    # - debug:
    #     var: ssh_key_file_exists_check.results[1].stat.exists

    - name: get ssh key to remove from the file
      set_fact:
        ssh_key_content: "{{ lookup('file', '/home/{{USER}}/.ssh/{{USER}}.pub') }}"
    
    - debug:
         var: ssh_key_content

- hosts: passwordless
  gather_facts: false
  vars:
    ssh_key_content_to_remove: "{{ lookup('file', '/home/{{USER}}/.ssh/{{USER}}.pub') }}"
  
  tasks:
    - name: delete the ssh key from the remote hosts
      lineinfile:
        path: /home/{{USER}}/.ssh/authorized_keys
        line: "{{ ssh_key_content_to_remove }}"
        state: absent
        backup: yes
      register: ssh_key_removal_execution
      
    # - debug:
    #     var: ssh_key_removal_execution

- hosts: local_host
  gather_facts: false

  tasks:
    - name: delete the 2 key files from local_host
      file:
        path: "/home/{{USER}}/.ssh/{{item}}"
        state: absent
      register: keys_deletion_execution
      with_items: 
        - "{{USER}}"
        - "{{USER}}.pub"

    # - debug:
    #     var: keys_deletion_execution

    - name: clear the ~/.ssh/config file
      lineinfile:
        path: "/home/{{USER}}/.ssh/config"
        line: "IdentityFile /home/{{USER}}/.ssh/{{USER}}"
        state: absent
        backup: yes
      register: ssh_config_file_key_deletion

    # - debug:
    #     var: ssh_config_file_key_deletion