---
- hosts: all
  become: "{{ USER }}"
  become_user: yes
  tasks:
    - name: check id
      shell: whoami
    - name: check .ssh local directory exists
      stat:
        path: "/home/{{USER}}/.ssh"
      register: ssh_directory_exists_check

    # - debug:
    #     var: ssh_directory_exists_check

    - name: Check needed OS tools exist
      shell: which sshpass ssh-keygen ssh-copy-id
      register: os_tools_exist
      ignore_errors: true

    - name: Fail execution if any of the needed OS tools is missing
      fail:
        msg: "One or more of the: sshpass, ssh-keygen, ssh-copy-id are missing on this machine. Please install them - using your distribution's recommended method - before continuing."
      when: os_tools_exist.rc != 0

    - name: create ~/.ssh local directory
      file:
        path: "/home/{{USER}}/.ssh"
        state: directory
        mode: "0700"
      register: ssh_directory_creation
      when: ssh_directory_exists_check is defined and ssh_directory_exists_check.stat.exists == false

    # - debug:
    #     var: ssh_directory_creation

    - name: check .ssh key file exists
      stat:
        path: "/home/{{USER}}/.ssh/{{item}}"
      register: ssh_key_file_exists_check
      with_items:
        - "{{USER}}"
        - "{{USER}}.pub"

    # - debug:
    #     var: ssh_key_file_exists_check.results[1].stat.exists

    - name: generate ssh key on local machine
      shell: "ssh-keygen -t rsa -f ~/.ssh/{{USER}} -P \"\""
      register: ssh_key_creation
      failed_when: ssh_key_creation.rc != 0
      when: ssh_key_file_exists_check is defined and ssh_key_file_exists_check.results[0].stat.exists == false and ssh_key_file_exists_check.results[1].stat.exists == false

    # - debug:
    #     var: ssh_key_creation

    - name: check .ssh/config file exists
      stat:
        path: "~/.ssh/config"
      register: ssh_config_file_exists_check

    # - debug:
    #     var: ssh_config_file_exists_check

    - name: create the ~/.ssh/config file
      file:
        path: "/home/{{USER}}/.ssh/config"
        state: touch
        mode: "0644"
      register: ssh_config_file_creation
      when: ssh_config_file_exists_check is defined and ssh_config_file_exists_check.stat.exists == false

    - name: add the new ssh key to the ~/.ssh/config file
      lineinfile:
        path: "/home/{{USER}}/.ssh/config"
        line: "IdentityFile ~/.ssh/{{USER}}"
        state: present
        backup: yes
      register: ssh_config_file_key_addition

    # - debug:
    #     var: ssh_config_file_key_addition

    - name: distribute the ssh key to the remote hosts
      shell: "sshpass -p \"{{PASSWORD}}\" ssh-copy-id -o StrictHostKeyChecking=no -i /home/{{USER}}/.ssh/{{USER}}.pub -p 22 \"{{USER}}@{{ HOSTS }}\""
      register: ssh_copy_id_execution
      with_items: 
        - "{{ HOSTS }}"
      failed_when: ssh_copy_id_execution.rc != 0

    # - debug:
    #     var: ssh_copy_id_execution

- hosts: ansible_setup_passwordless_setup_group
  gather_facts: false
  
  tasks:
    - name: check ssh to remote hosts works
      shell: "hostname; id"
      register: ssh_connection_test
      failed_when: ssh_connection_test.rc != 0

    - name: print the connectivity test results
      debug:
        var: ssh_connection_test.stdout_lines